### ISSUE TITLE
Criar o perfil de comunidade Open Source do projeto

### ISSUE THREAD

**Issue by fabiolamfleury** [fga-eps-mds/2019.2-Acacia#17]
### Descrição:

Adicionar documentação de comunidade do projeto para que ele atendam os padrões de projetos open source.

### Critérios de aceitação:

- O Readme deve representar o projeto de forma sucinta, ensinar como subir os diferentes tipos de ambientes e ajudar na navegação do projeto( Examplos: https://github.com/matiassingers/awesome-readme);
- A licença de software tem que ser aberta;
- O documento de contribuição deve referenciar as políticas do projeto e descrever a criação de issues;
- Todos membros devem ler e concordar com esses documentos.

### Tasks:

- [x]  Criar a descrição do projeto
- [x] Criar o código de conduta
- [x] Adicionar a licença do projeto
- [x] Adicionar o README
- [x] Mudar o nome 2019.2-TimeBolinho para 2019.2-Acacia
